---
name: CI build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build_and_push:

    runs-on: ubuntu-latest
    name: Build and push docker image

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Image tag from package.json
        id: image_tag
        run: echo ::set-output name=TAG::$(jq '.version' package.json | tr -d \")

      - name: Build and push image
        run: .github/dispatch_workflow.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "${{ secrets.TARGET_REPO }}"
          TAG: "${{ steps.image_tag.outputs.TAG }}"
          TARGET_WORKFLOW: "build_alertmanager_discord.yaml"
